server:
  port: 10015
  max-http-header-size: 8192
  tomcat:
    accesslog:
      enabled: true
      directory: access_log
      prefix: access_log
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" "%{X-Forwarded-For}i" "%{X-Real-IP}i" %D %S "%U" %v'
    basedir: ./
spring:
  application:
    name: movie-recommend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    username: root # 你的数据库用户名
    password: abc123 # 你的数据库密码，url中添加数据库地址和端口
    url: jdbc:mysql://localhost:3306/movietest?useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    #    username: root
    timeout: 5000
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        globally_quoted_identifiers: true
  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#  elasticsearch:
#    ip: 192.168.64.210
#    rest:
#      uris: 192.168.64.210:9200
#      username: root
#      password: abc123
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


es:
  host: localhost
  port: 9300
  cluster:
    name: elasticsearch
mongo:
  host: localhost
  port: 27017
redis:
  host: localhost



